name: 'FHIR IG Publish Action'
description: 'Run the FHIR IG Publisher as a GitHub Action'
author: 'Microsoft'
inputs:
  inputPath:
    description: 'Source path for IG Publisher, relative to root of the repo'
    default: 'input'
    required: false
  outputPath:
    description: 'Destination path for the IG Publisher, relative to the root of the repo'
    default: 'output'
    required: false
  
runs:
  using: 'java'
  main: 'dist/index.js'
